
services:
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: Dockerfile.gateway
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    networks:
      - app-network
    depends_on:
      - rabbitmq

  user:
    container_name: user
    build:
      context: ./
      dockerfile: Dockerfile.user
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - rabbitmq

  student:
    container_name: student
    build:
      context: ./
      dockerfile: Dockerfile.student
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - rabbitmq

  course:
    container_name: course
    build:
      context: ./
      dockerfile: Dockerfile.course
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - rabbitmq


  rabbitmq:   # ✅ now inside services
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
